# main.py
import argparse
import os
import frontmatter
import subprocess # New import
from .renderer import get_markdown_parser
from .templates import ARTICLE_TEMPLATE

def _compile_latex(filepath):
    """Compiles a .tex file to PDF using latexmk -xelatex."""
    print(f"Compiling '{filepath}' to PDF...")
    # latexmk will automatically find associated files if run in the same directory
    # or if given the full path. For robustness, let's change CWD for latexmk
    # to the directory of the .tex file.
    file_dir = os.path.dirname(filepath)
    file_name = os.path.basename(filepath)
    
    cmd = ["latexmk", "-xelatex", file_name]
    
    try:
        # Stream output to console instead of capturing
        result = subprocess.run(cmd, cwd=file_dir, check=True, stdout=None, stderr=None)
        print(f"Successfully compiled '{filepath}'.")
    except subprocess.CalledProcessError as e:
        print(f"Error compiling '{filepath}': latexmk returned non-zero exit code {e.returncode}.")
        print("Please check the LaTeXmk output above for details.")
        return False
    except FileNotFoundError:
        print(f"Error: 'latexmk' command not found. Please ensure LaTeXmk is installed and in your PATH.")
        return False
    return True

def _clean_latex(filepath):
    """Cleans auxiliary files generated by LaTeX compilation using latexmk -c."""
    print(f"Cleaning auxiliary files for '{filepath}'...")
    file_dir = os.path.dirname(filepath)
    file_name = os.path.basename(filepath)
    
    cmd = ["latexmk", "-c", file_name]
    
    try:
        # Stream output to console instead of capturing
        result = subprocess.run(cmd, cwd=file_dir, check=True, stdout=None, stderr=None)
        print(f"Successfully cleaned auxiliary files for '{filepath}'.")
    except subprocess.CalledProcessError as e:
        print(f"Error cleaning auxiliary files for '{filepath}': latexmk returned non-zero exit code {e.returncode}.")
        print("Please check the LaTeXmk output above for details.")
        return False
    except FileNotFoundError:
        print(f"Error: 'latexmk' command not found. Please ensure LaTeXmk is installed and in your PATH.")
        return False
    return True


def convert_md_to_tex(input_path, output_path):
    # Ensure output directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # 1. 读取 Markdown 文件
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            full_md_content = f.read() # Read full content to parse frontmatter
    except FileNotFoundError:
        print(f"Error: File '{input_path}' not found.")
        return False # Indicate failure

    # Parse frontmatter
    post = frontmatter.loads(full_md_content)
    md_content_body = post.content # Extract Markdown body
    metadata = post.metadata

    # Extract metadata with defaults
    title = metadata.get("title", "Untitled Document")
    subtitle = metadata.get("subtitle", "")
    author = metadata.get("author", "Unknown Author")

    # Conditionally format subtitle for LaTeX template
    subtitle_formatted = f"\\large \\textsf{{—— {subtitle} ——}}" if subtitle else ""
    
    # 2. 解析并转换内容 (AST -> LaTeX Body)
    parser = get_markdown_parser()
    tex_body = parser(md_content_body) # Use content body here

    # 3. 填充到完整模版中
    full_tex = ARTICLE_TEMPLATE % {
        "title": title,
        "subtitle_formatted": subtitle_formatted, # Use the new formatted key
        "author": author,
        "content": tex_body
    }

    # 4. 写入结果
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(full_tex)
    
    print(f"Successfully converted '{input_path}' to '{output_path}'")
    return True # Indicate success

def main():
    # 设置命令行参数
    parser = argparse.ArgumentParser(description="Convert Markdown to LaTeX and optionally compile/clean.")
    parser.add_argument("input", help="Path to input Markdown file")
    parser.add_argument("-o", "--output", help="Path to output TeX file")
    parser.add_argument("--compile", action="store_true", 
                        help="Compile the generated .tex file to PDF using xelatex via latexmk.")
    parser.add_argument("--clean", action="store_true", 
                        help="Clean auxiliary files generated by LaTeX compilation using latexmk -c. "
                             "This runs after compilation if --compile is also used and successful.")

    args = parser.parse_args()

    input_file = args.input
    # 如果没指定输出文件名，默认将 input.md 改为 doc/input.tex
    if args.output:
        output_file = args.output
    else:
        # Determine default output path in 'doc' directory
        base_name = os.path.basename(input_file)
        file_name_no_ext = os.path.splitext(base_name)[0]
        output_file = os.path.join("doc", file_name_no_ext + ".tex")

    # 1. Convert Markdown to TeX
    conversion_successful = convert_md_to_tex(input_file, output_file)

    # 2. Optionally compile and clean
    if conversion_successful: # Only proceed if MD to TeX conversion was successful
        if args.compile:
            compilation_successful = _compile_latex(output_file)
            if compilation_successful and args.clean:
                _clean_latex(output_file) # Clean after successful compile if --clean is also requested
        elif args.clean: # If --clean is requested alone, and not part of a compile flow
            _clean_latex(output_file)


if __name__ == "__main__":
    main()